version: '3'
services:
  gitlab:
    image: 'gitlab/gitlab-ce:13.0.6-ce.0'
    container_name: 'gitlab-ce'
    restart: always
    hostname: 'gitlab'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.io'
        prometheus['listen_address'] = "0.0.0.0:9090"
        prometheus['enable'] = true
        gitaly['prometheus_listen_addr'] = "0.0.0.0:9236"
        node_exporter['listen_address'] = "0.0.0.0:9101"
        redis_exporter['listen_address'] = "0.0.0.0:9121"
        postgres_exporter['listen_address'] = "0.0.0.0:9187"
        gitlab_rails['time_zone'] = "Asia/Singapore"
        gitlab_rails['backup_keep_time'] = 172800   
        grafana['admin_password'] = "Passw0rd"
        grafana['enable'] = true
        letsencrypt['enable'] = false
        letsencrypt['auto_renew'] = false
        nginx['listen_port'] = 443
        nginx['redirect_http_to_https'] = true
        nginx['ssl_certificate'] = "/etc/ssl/certs/gitlab/gitlab.io.crt"
        nginx['ssl_certificate_key'] = "/etc/ssl/certs/gitlab/gitlab.io.key"
        nginx['ssl_protocols'] = "TLSv1.1 TLSv1.2"
        nginx['client_max_body_size'] = '0'
      # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '<Host IP:Port>:80'
      - '<Host IP:Port>:443'
      - '<Host IP:Port>:22'
      - '<Host IP:Port>:9090' #Prometheus listen port
      - '<Host IP:Port>:9168' #Gitlab exporter
      - '<Host IP:Port>:9236' #Prometheus exporter
      - '<Host IP:Port>:9100' #Node exporter
      - '<Host IP:Port>:9121' #Redis exporter
      - '<Host IP:Port>:9187' #Psql exporter
      - '<Host IP:Port>:8060' #Nginx 
      - '<Host IP:Port>:8082' #Sidekiq exporter
    volumes:
      - '<Gitlab Working Directory>/config:/etc/gitlab'
      - '<Gitlab Working Directory>/logs:/var/log/gitlab'
      - '<Gitlab Working Directory>/data:/var/opt/gitlab'     
      - '<Gitlab Working Directory>/volume_data/ssl:/etc/ssl/certs/gitlab'

